name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Extraer código del repositorio
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        # Comandos para ejecutar tus pruebas aquí
