name: Publish

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Extraer código del repositorio
      uses: actions/checkout@v3

    - name: Configurar versión de Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org/'

    - name: Publish to NPM
      run: npm publish
      env:
        PACKAGE_SECRET: ${{secrets.PACKAGE_SECRET}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Set up Node.js for GitHub Packages
      uses: actions/setup-node@v3
      with:
        node-version: 14
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@dmartinezh97'