name: Release

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Comprobar el patrón de etiquetas v*
      id: check_tag
      run: |
        TAG_NAME=${{ github.ref }}
        if [[ $TAG_NAME == refs/tags/v* ]]; then
          echo "This is a valid release tag. Proceeding with release..."
          echo "::set-output name=valid::true"
        else
          echo "This is not a release tag. Skipping release..."
          echo "::set-output name=valid::false"
        fi

    - name: Crear Release
      if: steps.check_tag.outputs.valid == 'true'
      run: |
        # Comandos para crear una release aquí