name: Release Workflow

on:
  workflow_run:
    workflows: ["Test Workflow"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      run: |
        # Comandos para crear una release aquí
