name: 02 - Publicar en GitHub Packages

on:
  push:
      branches:
        - main
#   workflow_run:
#     workflows: ["01 - Test"]
#     types:
#       - completed

jobs:
  build:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    # - name: Extraer código del repositorio
      - uses: actions/checkout@v3
    # - name: Configurar versión de Node.js para publicar en Github Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: JS-Devtools/npm-publish@v2
        with:
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_SECRET }}