name: 02 - Publicar en GitHub Packages

on:
  workflow_run:
    workflows: ["01 - Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    # - name: Extraer código del repositorio
      - uses: actions/checkout@v3
    # - name: Configurar versión de Node.js para publicar en Github Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # - name: Instalar dependencias
    #   run: npm install

    # - name: Build
    #   run: npm run build

    # - name: Publicar en GitHub Packages
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GIT_SECRET }}