name: 01 - Test

on:
  push:
    branches:
      - test #main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Extraer código del repositorio
      uses: actions/checkout@v3

    - name: Ejecutar tests
      run: |
        # Comandos para ejecutar tus pruebas aquí
